# Base configuration for the trigger algorithm

IO:
  sn_data_dir: /eos/project-e/ep-nu/pbarhama/sn_saves/jun24_snnue_pds/
  bg_data_dir: /eos/project-e/ep-nu/pbarhama/sn_saves/jun24_vd_background_juergen/
  save_dir: /eos/home-p/pbarhama/myway/saved_effs/

  output_name_data: None
  output_name_curve: None
  input_name: None # Input for when calculating the efficiency curve

  # Auxiliary pickles (and other stuff) and .dat for coordinates
  # aux_coordinate_dir: /eos/home-p/pbarhama/myway/detector_coordinates/
  # aux_data_dir: /eos/home-p/pbarhama/myway/aux_pickles/
  aux_coordinate_dir: ../aux_data/detector_coordinates/
  aux_data_dir: ../aux_data/

Detector:
  # Detector type: HD or VD
  type: VD
  geometry_version: v5 # this now does nothing
  # Used volume in real-life TPCs
  true_tpc_sizes: 
    VD: 10
    HD: 10
  # Used volume for the simulation geometries
  used_tpc_sizes:
    VD: 2.6
    HD: 1.2
  # Correcting for the fact that TPCs are actually a bit bigger than 10kt
  tpc_size_correction_factor: 1.2
  # Correction for extra volume outside of the active volume (buffer region)
  sn_event_multiplier: 1.17

Physics:
  # Pinching parameters (neutrino flux)
  # TODO: Ability to add an arbitrary flux
  # GKVM 23 5
  # LIVERMORE 14.4 2.8
  # GARCHING 12.2 4.5 (OR 11.44 and 3.2)
  neutrino_flux:
    average_energy: 23.0
    alpha: 5.0

  # Interaction numbers for a 40kton LArTPC at 10 kpc
  # Values of v_e-CC interactions at 10 kpc for a 40 kton LArTPC
  interaction_number_10kpc:
    LIVERMORE: 2684
    GKVM: 3295
    GARCHING: 882

Simulation:
  # Number of files to load for parameter search
  sn_file_limit_parameter_search: 10
  bg_file_limit_parameter_search: 20
  # Number of files to load for efficiency estimation once optimal parameters are found
  sn_file_limit: 10
  bg_file_limit: 20

  # Clustering parameters over which to search for optimization
  max_cluster_times: [0.15, 0.2] # In microseconds
  max_hit_time_diff: [0.25, 0.20] # In microseconds
  max_hit_distances: [200, 220] # In cm
  lower_min_hit_multiplicity: 8 # Minimum number of hits in a cluster
  upper_min_hit_multiplicity: 13
  classifier_thresholds: [0.5, 0.7, 0.9]
  classifier_hist_type: hit_multiplicity #"hit_multiplicity" or "bdt"
  statistical_method: chi2 # TODO: add gaussian vs poissonian

  # Distances over which to calculate the efficiency (if any)
  eff_curve:
    calculate: True
    mode: from_scratch # from_scratch, from_data
    distances:
      min: 4
      max: 40
      step: 4

  # Use BDT?
  bdt:
    use: true
    energy_limit: 30

  # ----- Parameters below are less likely to be changed ----
  fake_trigger_rate: 3.85802469e-7 # 1/(60 * 60 * 24 * 30) -> 1 trigger per month
  burst_time_window: 1.0e+6 # microseconds
  distance_to_optimize: 20.0 # kpc
  sim_mode: xe # 'xe' or 'aronly'
  adc_mode: normal # Useless at this point

Backgrounds:
  VD:
    - Ar39GenInLAr
    - Kr85GenInLAr
    - Ar42GenInLAr
    - K42From42ArGenInLAr
    - Rn222ChainRn222GenInLAr
    - Rn222ChainPo218GenInLAr
    - Rn222ChainPb214GenInLAr
    - Rn222ChainBi214GenInLAr
    - Rn222ChainPb210GenInLAr
    - Rn220ChainPb212GenInLAr
    - K40GenInCathode
    - U238ChainGenInCathode
    - Th232ChainGenInCathode
    - K40GenInAnode
    - U238ChainGenInAnode
    - Th232ChainGenInAnode
    - Rn222ChainGenInPDS
    - K42From42ArGenInUpperMesh1x8x14
    - Rn222ChainFromPo218GenInUpperMesh1x8x14
    - Rn222ChainFromPb214GenInUpperMesh1x8x14
    - Rn222ChainFromBi214GenInUpperMesh1x8x14
    - Rn222ChainFromPb210GenInUpperMesh1x8x14
    - Rn222ChainFromBi210GenInUpperMesh1x8x14
    - Rn220ChainFromPb212GenInUpperMesh1x8x14
    - CavernwallGammasAtLAr1x8x14
    - foamGammasAtLAr1x8x14
    - CavernwallNeutronsAtLAr1x8x14
    - CryostatNGammasAtLAr1x8x14
    - CavernNGammasAtLAr1x8x14

  HD:
    - Ar39GenInLAr
    - Kr85GenInLAr
    - Ar42GenInLAr
    - K42From42ArGenInLAr
    - Rn222ChainRn222GenInLAr
    - Rn222ChainPo218GenInLAr
    - Rn222ChainPb214GenInLAr
    - Rn222ChainBi214GenInLAr
    - Rn222ChainPb210GenInLAr
    - Rn220ChainPb212GenInLAr
    - K40GenInCPA
    - U238ChainGenInCPA
    - K42From42ArGenInCPA
    - Rn222ChainPo218GenInCPA
    - Rn222ChainPb214GenInCPA
    - Rn222ChainBi214GenInCPA
    - Rn222ChainPb210GenInCPA
    - Rn222ChainFromBi210GenInCPA
    - Rn220ChainFromPb212GenInCPA
    - Co60GenInAPA
    - U238ChainGenInAPA
    - Th232ChainGenInAPA
    - K40GenInAPAboards
    - U238ChainGenInAPAboards
    - Th232ChainGenInAPAboards
    - Rn222ChainGenInPDS
    - CavernwallGammasAtLAr
    - foamGammasAtLAr
    - CavernwallNeutronsAtLAr
    - CryostatNGammasAtLAr
    - CavernNGammasAtLAr
