# Some configuration for the trigger algorithm

# Default config file. 
# The values not explicitly declared in this file will be pulled from this config.
DEFAULT_CONFIG_FILE: default_config_vd.yaml

Simulation:
  clustering:
    mode: "single"
    parameters:
      max_cluster_time: 0.25 # In microseconds
      max_hit_time_diff: 0.2 # In microseconds
      max_hit_distance: 350 # In cm
      min_hit_multiplicity: 8
      min_neighbours: 1



  